name: Apply to all Greenbone repositories

on:
  workflow_dispatch:

jobs:
  apply-to-all-repos:
    name: Apply to all Greenbone repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # gh repo list greenbone --no-archived --limit 320
        repository:
          - greenbone/vulnerability-tests
          - greenbone/scan-agent-commons
          - greenbone/gsm-management-console-connector
          - greenbone/gvm-tools
          - greenbone/opensight-network
          - greenbone/python-project-template
          - greenbone/mattermost-notify
          - greenbone/opensight-proxy
          - greenbone/greenbone-container-images
          - greenbone/opensight-os-releaser
          - greenbone/autohooks-plugin-isort
          - greenbone/autohooks-plugin-mypy
          - greenbone/opensight-os-api-lib
          - greenbone/opensight-backup
          - greenbone/opensight-service
          - greenbone/opensight-upgrade
          - greenbone/opensight-installer
          - greenbone/autohooks-plugin-black
          - greenbone/autohooks-plugin-ruff
          - greenbone/autohooks-plugin-pylint
          - greenbone/autohooks
          - greenbone/autohooks-plugin-flake8
          - greenbone/actions
          - greenbone/openvas-scanner
          - greenbone/automatix
          - greenbone/openvas-install
          - greenbone/pontos
          - greenbone/workflows
          - greenbone/opensight-container-management
          - greenbone/opensight-golang-libraries
          - greenbone/csaf_distribution
          - greenbone/agentix
          - greenbone/vulnerability-intelligence-data-enrichment
          - greenbone/opensight-notification-service
          - greenbone/management-console-frontend
          - greenbone/notus-data
          - greenbone/vulnerability-tests-updater
          - greenbone/notus-generator
          - greenbone/vt-cve-library
          - greenbone/scap-data
          - greenbone/opensight-frontend-components
          - greenbone/management-console-backend
          - greenbone/gvm-libs
          - greenbone/greenbone-feed-sync
          - greenbone/pheme
          - greenbone/python-gvm
          - greenbone/troubadix
          - greenbone/greenbone-scap
          - greenbone/greenbone-scap-api
          - greenbone/gsa
          - greenbone/websocket-tunnel
          - greenbone/opensight-postgres
          - greenbone/management-console-connector
          - greenbone/sboms
          - greenbone/hidden-unicode-scanner
          - greenbone/cert-bund-data
          - greenbone/vt-cve-feeder
          - greenbone/dfn-cert-data
          - greenbone/cloud-web-frontend
          - greenbone/cloud-vmsp-admin-web-frontend
          - greenbone/cloud-dynamic-table
          - greenbone/cloud-extern-web-frontend
          - greenbone/cloud-msp-admin-web-frontend
          - greenbone/cloud-component-library
          - greenbone/cloud-resolve-os
          - greenbone/cloud-react-chartist
          - greenbone/cloud-chart-library
          - greenbone/devops
          - greenbone/gvm-libs-pipeline-test
          - greenbone/gea-experiments
          - greenbone/cloud-schedule-service
          - greenbone/cloud-billing-service
          - greenbone/cloud-task-execution-service
          - greenbone/cloud-user-management-service
          - greenbone/cloud-notification-service
          - greenbone/cloud-vmsp-admin-service
          - greenbone/cloud-target-service
          - greenbone/cloud-gateway-management-service
          - greenbone/cloud-host-validation-service
          - greenbone/cloud-credentials-service
          - greenbone/cloud-limitation-service
          - greenbone/cloud-gmsp-admin-service
          - greenbone/cloud-gsc-vpn-gateway-frontend
          - greenbone/cloud-msp-admin-service
          - greenbone/cloud-task-export-service
          - greenbone/cloud-gsc-vpn-gateway-manager
          - greenbone/cloud-authentication-context
          - greenbone/cloud-task-dispatcher-service
          - greenbone/scan-agent-app
          - greenbone/scan-agent-updater
          - greenbone/asset-management-backend
          - greenbone/gos-system
          - greenbone/bizgpt
          - greenbone/gos-vpn
          - greenbone/gos-labels
          - greenbone/gsad
          - greenbone/gos-pyspatch
          - greenbone/vulnerability-intelligence-backend
          - greenbone/gvmd
          - greenbone/automatix-actions
          - greenbone/datawarehouse-pipelines
          - greenbone/cloud-ip-library
          - greenbone/cloud-key-cloak-api
          - greenbone/scan-agent-scripts
          - greenbone/vulnerability-intelligence-frontend
          - greenbone/gsm-openvas
          - greenbone/pipeline-experiments
          - greenbone/data-objects
          - greenbone/agent-control
          - greenbone/gsm-linux-image
          - greenbone/asset-management-frontend
          - greenbone/gos-logging
          - greenbone/gsm-websocket-tunnel
          - greenbone/scanner-api
          - greenbone/nasl-generator
          - greenbone/gos-upgrade
          - greenbone/gos-feed
          - greenbone/gos-selfcheck
          - greenbone/gos-integrity-check
          - greenbone/opensight-e2e
          - greenbone/opensight-os-ci
          - greenbone/gos-fume
          - greenbone/autohooks-plugin-pytest
          - greenbone/gos-libs
          - greenbone/greenbone-sbominator
          - greenbone/gos-state-manager
          - greenbone/gos-shepherd
          - greenbone/docs
          - greenbone/gosctl
          - greenbone/gsm-manual
          - greenbone/vt-test-environments
          - greenbone/pg-gvm
          - greenbone/notus-scanner
          - greenbone/cloud-user-context
          - greenbone/cloud-rest-util
          - greenbone/ospd-openvas
          - greenbone/greenbone-license-service
          - greenbone/skiron-data
          - greenbone/gsm-agent-control
          - greenbone/opensight-os-manual
          - greenbone/gos-network
          - greenbone/production-apgen
          - greenbone/cloud-task-report-service
          - greenbone/cloud-user-secured-jpa-entities
          - greenbone/cloud-ddd-util
          - greenbone/cloud-crypto-utils
          - greenbone/cloud-static-resource-service
          - greenbone/openvas-view-e2e
          - greenbone/gsm-greenbone-vulnerability-manager
          - greenbone/gsm-greenbone-vulnerability-management-libraries
          - greenbone/greenbone-enterprise-ceno-siesta
          - greenbone/gos-webserver-config
          - greenbone/gos-snmpd
          - greenbone/gos-sourcefire-connector
          - greenbone/gsm-ospd-openvas
          - greenbone/opensight-notification-frontend
          - greenbone/user-management-frontend
          - greenbone/gos-base-files
          - greenbone/gos-info
          - greenbone/gos-flash
          - greenbone/gos-master
          - greenbone/gos-backup
          - greenbone/gos-sensor
          - greenbone/gos-power
          - greenbone/gos-setup
          - greenbone/gos-sshd
          - greenbone/gos-support
          - greenbone/gos-cli-admin
          - greenbone/gos-ansible
          - greenbone/skiron
          - greenbone/gsm-settings
          - greenbone/gsm-features
          - greenbone/gos-ci-images
          - greenbone/gcs-msp-manual
          - greenbone/gsm-rescue
          - greenbone/gos-ci-tarballs
          - greenbone/gsm-skiron
          - greenbone/keycloak-client-golang
          - greenbone/opensight-asset-manual
          - greenbone/opensight-os-packages
          - greenbone/qm-gmp-robot
          - greenbone/greenbone-support-package-docs
          - greenbone/poc-playbook
          - greenbone/gcs-user-manual
          - greenbone/opensight-keycloak
          - greenbone/datalake-pipelines
          - greenbone/openvas-control-manual
          - greenbone/gcs-vmsp-manual
          - greenbone/opensight-lookout-manual
          - greenbone/datawarehouse-transformations
          - greenbone/scan-agent-installer
          - greenbone/report-formats
          - greenbone/pheme-report-formats
          - greenbone/architecture-board
          - greenbone/user-management-backend
          - greenbone/tech-doc-portal
          - greenbone/github-runners
          - greenbone/dev-cache
          - greenbone/gos-debug
          - greenbone/devops-ansible
          - greenbone/gos-network-manager
          - greenbone/gsm-greenbone-security-assistant
          - greenbone/opensight-os-infrastructure
          - greenbone/openvas-install-ui
          - greenbone/openvas-website
          - greenbone/cloud-task-service
          - greenbone/cloud-gsc-node-manager
          - greenbone/opensight-os-iso
          - greenbone/gos-manual
          - greenbone/datawarehouse-input
          - greenbone/cloud-gsc-docker-manager
          - greenbone/gsm-openssh
          - greenbone/gsm-gvm-tools
          - greenbone/greenbone-license-service-ui
          - greenbone/techop-gvm-tools-signing
          - greenbone/gsm-python-gvm
          - greenbone/gsm-pheme
          - greenbone/qm-feed-tests
          - greenbone/agent-control-docs
          - greenbone/appliance-simulator
          - greenbone/go-project-template
          - greenbone/cloud-gsc-vpn-cli
          - greenbone/feed-deployment-pipeline
          - greenbone/opensight-identifier
          - greenbone/asset-management-browser
          - greenbone/greenbone-docker
          - greenbone/scanner-lab
          - greenbone/cloud-validation-library
          - greenbone/opensight-ingress
          - greenbone/opensight-opensearch
          - greenbone/keycloak-mock-server
          - greenbone/qm-browser-tests
          - greenbone/gos-debian-archive-keyring
          - greenbone/gos-relizah
          - greenbone/gretl
          - greenbone/container-scanning
          - greenbone/gos-virtual
          - greenbone/gos-hardware
          - greenbone/openvas-smb
          - greenbone/old-greenbone-enterprise-container
          - greenbone/gsm-greenbone-security-assistant-daemon
          - greenbone/cloud-e2e
          - greenbone/greenbone-enterprise-container
          - greenbone/cloud-gsc-vpn-updater
          - greenbone/runner-images
          - greenbone/gsm-pg-gvm
          - greenbone/devops-analytix
          - greenbone/greenbone-license-service-bdd
          - greenbone/gos-gvmcg
          - greenbone/gos-grub
          - greenbone/gos-lcd
          - greenbone/gsm-openvas-smb
          - greenbone/gos-initramfs-config
          - greenbone/gsm-lcdproc
          - greenbone/gos-grub-protection
          - greenbone/gsm-isc-dhcp
          - greenbone/exercise-admin-notification
          - greenbone/gsm-notus-scanner
          - greenbone/gsm-greenbone-vulnerability-management-libraries-pipeline-test
          - greenbone/gsm-boreas-cli
          - greenbone/gos-nsis-gsm-plugins
          - greenbone/gos-vfire-connector
          - greenbone/gos-command-wrapper
          - greenbone/gos-verinice-connector
          - greenbone/gos-timesync
          - greenbone/gsm-pyroute2
          - greenbone/gsm-python3-pycha
          - greenbone/gos-project-manager
          - greenbone/gos-autopkgtest-lxc
          - greenbone/gos-buildsystem-ansible-roles
          - greenbone/gos-ci
          - greenbone/techops-scripts
          - greenbone/frontend-applicant-task-backend
          - greenbone/sboms2
          - greenbone/gsm-libmicrohttpd
          - greenbone/.github
          - greenbone/cloud-behaviour-tests
          - greenbone/cloud-keycloak-theme
          - greenbone/cloud-api-examples
          - greenbone/playground
          - greenbone/agent-control-demo
          - greenbone/lookout-perfomance-tests
          - greenbone/platforms-automatic-gvm-stack-builder
          - greenbone/cloud-gsc-gateway-manager
          - greenbone/cloud-default-backend-service
          - greenbone/cloud-gsc-node-switch-manager
          - greenbone/boreas
          - greenbone/cloud-gsc-docker-openvas
          - greenbone/cloud-rsyslog
          - greenbone/cloud-api-documentation
          - greenbone/cloud-spinnaker-deployment
          - greenbone/cloud-manual-server
          - greenbone/gos-mosquitto
          - greenbone/ps-testing
          - greenbone/ps-production
          - greenbone/cloud-full-text-search
          - greenbone/Abschlussprojekt_Gabriel
          - greenbone/gos-lintian
          - greenbone/cloud-spring-parent-pom
          - greenbone/techops-nginx-configs
          - greenbone/templates
          - greenbone/att-feed-check
          - greenbone/osbom
          - greenbone/cloud
          - greenbone/gos-theia
          - greenbone/greenbone.github.io
          - greenbone/scan-management-e2e-test
          - greenbone/gsm-weasyprint
          - greenbone/gsm-sentry-python
          - greenbone/gsm-sentry-native
          - greenbone/gsm-libtheia
          - greenbone/gos-initramfs-tools
          - greenbone/sysops-rss-to-email


    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: workflows

      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.repository }}
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}

      - name: Checkout branch, Commit and Push
        shell: bash
        working-directory: ${{ github.workspace }}/${{ matrix.repository }}
        run: |
          git config user.email "${{ secrets.GREENBONE_BOT_MAIL }}"
          git config user.name "${{ secrets.GREENBONE_BOT_USERNAME }}"
          git push origin -d automated-general-changes || true
          git pull
          git checkout main
          git checkout -b automated-general-changes
          mkdir -p .github/workflows
          cp ${{ github.workspace }}/workflows/.github/workflows/detect-hidden-unicode.yml .github/workflows
          git add .github/workflows/detect-hidden-unicode.yml
          git commit -am "Fix  Add or Update detect-hidden-unicode.yml"
          git push --set-upstream origin automated-general-changes
        env:
          GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}

      - name: Create Labels
        shell: bash
        working-directory: ${{ github.workspace }}/${{ matrix.repository }}
        run: |
          gh label create automated --description "Items with this label are created automatically" --color 352AD1 --force
          gh label create general --description "Items with this label are created by a general workflow in greenbone/workflows" --color 3BD12A --force
        env:
          GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}

      - name: Create PR
        shell: bash
        working-directory: ${{ github.workspace }}/${{ matrix.repository }}
        run: |
          gh pr create --reviewer "@greenbone/devops" --label automated --label general --fill --head automated-general-changes --title "Fix  Add or Update detect-hidden-unicode.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}

     #- name: Approve PR
     #  shell: bash
     #  working-directory: ${{ github.workspace }}/${{ matrix.repository }}
     #  run: |
     #    gh pr review automated-general-changes --approve
     #  env:
     #    GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

     #- name: Merge PR
     #  shell: bash
     #  working-directory: ${{ github.workspace }}/${{ matrix.repository }}
     #  run: |
     #    gh pr merge --auto automated-general-changes --squash
     #  env:
     #    GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}
