name: Apply to all Greenbone repositories

on:
  workflow_dispatch:

jobs:
  apply-to-all-repos:
    name: Apply to all Greenbone repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO Add the rest of the repositories
        repository:
          - greenbone/pontos

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: workflows

      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.repository }}

      - name: Checkout branch, Commit and Push
        shell: bash
        working-directory: ${{ github.workspace }}/${{ matrix.repository }}
        run: |
          git config user.email "${{ secrets.GREENBONE_BOT_MAIL }}"
          git config user.name "${{ secrets.GREENBONE_BOT_USERNAME }}"
          git push origin -d automated-general-changes || true
          git pull
          git checkout main
          git checkout -b automated-general-changes
          mkdir -p .github/workflows
          cp ${{ github.workspace }}/workflows/.github/workflows/detect-hidden-unicode.yml .github/workflows
          git add .github/workflows/detect-hidden-unicode.yml
          git commit -am "Fix: Add or Update detect-hidden-unicode.yml"
          git push --set-upstream origin automated-general-changes
        env:
          GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}

      - name: Create PR
        shell: bash
        working-directory: ${{ github.workspace }}/${{ matrix.repository }}
        run: |
          gh pr create --reviewer "@greenbone/devops" --label automated --label general --fill --head automated-general-changes --title "Fix: Add or Update detect-hidden-unicode.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}

     #- name: Approve PR
     #  shell: bash
     #  working-directory: ${{ github.workspace }}/${{ matrix.repository }}
     #  run: |
     #    gh pr review automated-general-changes --approve
     #  env:
     #    GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

     #- name: Merge PR
     #  shell: bash
     #  working-directory: ${{ github.workspace }}/${{ matrix.repository }}
     #  run: |
     #    gh pr merge --auto automated-general-changes --squash
     #  env:
     #    GITHUB_TOKEN: ${{ secrets.GREENBONE_BOT_TOKEN }}
