name: Activate Auto-Merge on a PR

on: 
  pull_request_target:
  workflow_call:
    secrets:
      GREENBONE_BOT_TOKEN:
        required: true
    inputs:
      merge-type:
        description: "What type of merge, do you want to do? [squash, rebase] default: squash"
        default: "squash"
        required: false
        type: string


permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for open PRs
        run: gh pr merge --auto ${{ inputs.merge-type }} "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GREENBONE_BOT_TOKEN}}
