name: Check project versioning

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.10"
        type: string

jobs:
  check-version:
    name: Check versioning for consistency
    runs-on: "ubuntu-latest"
    steps:
      - uses: greenbone/actions/check-version@1e7f352e793c3815c54aebe8f9da50d7a80e6f41  # v3.36.18
        with:
          python-version: ${{ inputs.python-version }}
