name: Check project versioning

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.10"
        type: string

jobs:
  check-version:
    name: Check versioning for consistency
    runs-on: "ubuntu-latest"
    steps:
      - uses: greenbone/actions/check-version@41ce222ededcb84b9ee4f4b532083c69de062a01  # v3.36.13
        with:
          python-version: ${{ inputs.python-version }}
