name: Check project versioning

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.10"
        type: string

jobs:
  check-version:
    name: Check versioning for consistency
    runs-on: "ubuntu-latest"
    steps:
      - uses: greenbone/actions/check-version@a1883bd24d2d921426b3f06413e84606ecd43bdd  # v3.27.11
        with:
          python-version: ${{ inputs.python-version }}
