name: Check project versioning

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.10"
        type: string

jobs:
  check-version:
    name: Check versioning for consistency
    runs-on: "ubuntu-latest"
    steps:
      - uses: greenbone/actions/check-version@aa49604a7c2a28d7810d23addac6513af7d8e11f  # v3.36.12
        with:
          python-version: ${{ inputs.python-version }}
