name: Check and test

on:
  workflow_call:
    inputs:
      lint-packages:
        description: "Names of the Python packages to be linted"
        type: string
      mypy-arguments:
        description: "Additional arguments to mypy"
        default: ""
        type: string
      python-version:
        description: "Python version to use"
        default: "3.10"
        type: string
      test-command:
        description: "Command to run the unit tests"
        default: "python -m unittest -v"
        type: string

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/lint-python.yml
    with:
      lint-packages: ${{ inputs.lint-packages }}
      python-version: ${{ inputs.python-version }}

  test:
    name: Run tests
    uses: ./.github/workflows/test-python.yml
    with:
      python-version: ${{ inputs.python-version }}
      test-command: ${{ inputs.test-command }}

  mypy:
    name: Check type information
    uses: ./.github/workflows/typing-python.yml
    with:
      mypy-arguments: ${{ inputs.mypy-arguments }}
      python-version: ${{ inputs.python-version }}
