name: Container build and push ghcr.io

on:
  workflow_call:
    inputs:
      image-labels:
        description: "Image labels."
        type: string
        required: true
      image-url:
        description: "Image registry url to push to."
        type: string
        required: true
      image-tags:
        description: "Image tags."
        type: string
        required: true
      image-platforms: 
        description: "Image platforms to build for."
        type: string
        default: linux/amd64
      build-context: 
        description: "Path to image build context."
        type: string
        default: .
      build-docker-file:
        description: "Path to the docker file."
        type: string
        default: ./Dockerfile

jobs:
  building:
    name: Container build and push ghcr.io
    uses: greenbone/workflows/.github/workflows/container-build-generic.yml@pholthaus/docker
    with:
      image-url: ${{ vars.IMAGE_REGISTRY }}/${{ github.repository }}
      image-labels: |
        org.opencontainers.image.vendor=Greenbone
        org.opencontainers.image.base.name=alpine/latest
      image-tags: |
        # create container tag for git tags
        type=ref,event=tag,value=latest
        type=match,pattern=v(.*),group=1
        type=ref,event=pr
        # use unstable for main branch
        type=raw,value=unstable,enable={{is_default_branch}}
      registry: ${{ vars.IMAGE_REGISTRY }}
      registry-username: ${{ github.actor }}
      image-platforms: ${{ inputs.image-platforms }}
      build-context: ${{ inputs.build-context }}
      build-docker-file: ${{ inputs.build-docker-file }}
    secrets: 
     REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }} 

