name: Sensor Build and Push

on:
  workflow_call:
    inputs:
      ref-name:
        description: "The ref to build a container image from. For example a tag v23.0.0."
        required: false
        type: string
      build-context:
        description: "Path to image build context. Default is ."
        default: .
        type: string
      build-docker-file:
        description: "Path to the docker file. Default is .docker/prod.Dockerfile"
        default: .docker/prod.Dockerfile
        type: string
      image-labels:
        description: "Image labels."
        required: true
        type: string
      image-url:
        description: "Image url/name without registry."
        required: true
        type: string
      notify:
        description: "Enable mattermost notify. Default is true"
        default: "true"
        type: string

    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false
      GREENBONE_REGISTRY:
        required: false
      GREENBONE_REGISTRY_USER:
        required: false
      GREENBONE_REGISTRY_TOKEN:
        required: false
      MATTERMOST_WEBHOOK_URL:
        required: false

jobs:
  build:
    runs-on: self-hosted-generic
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ inputs.ref-name }}

      - uses: greenbone/actions/is-latest-tag@v3
        id: latest
        with:
          tag-name: ${{ inputs.ref-name }}

      - name: Set container build options
        id: container-opts
        run: |
          if [[ "${{ github.ref_type }}" = 'tag' ]]; then
            echo "version=stable" >> $GITHUB_OUTPUT
            echo "gvm-libs-version=oldstable" >> $GITHUB_OUTPUT
          else
            echo "version=edge" >> $GITHUB_OUTPUT
            echo "gvm-libs-version=oldstable-edge" >> $GITHUB_OUTPUT
          fi

      - name: Container build and push 3rd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-generic@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          build-args: |
            VERSION=${{ steps.container-opts.outputs.version }}
            GVM_LIBS_VERSION=${{ steps.container-opts.outputs.gvm-libs-version }}
            IMAGE_REGISTRY=${{ vars.IMAGE_REGISTRY }}
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          cosign-tlog-upload: "false"
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge
            type=ref,event=pr
            type=raw,value=latest,enable=${{ steps.latest.outputs.is-latest-tag == 'true' }}
            type=raw,value=stable,enable=${{ steps.latest.outputs.is-latest-tag == 'true' }}
          image-platforms: ${{ matrix.platform }}
          registry: ${{ secrets.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}
          scout-user: ${{ secrets.DOCKERHUB_USERNAME }}
          scout-password: ${{ secrets.DOCKERHUB_TOKEN }}
          scout-command: cves

  notify:
    needs:
      - build
    if: ${{ !cancelled() && startsWith(github.ref, 'refs/tags/v')  && startsWith(inputs.notify, 'true') }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-3rd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    secrets: inherit
