name: Sensor Build and Push

on:
  workflow_call:
    inputs:
      ref-name:
        description: "The ref to build a container image from. For example a tag v23.0.0."
        type: string
      build-context:
        description: "Path to image build context. Default is ."
        default: .
        type: string
      build-docker-file:
        description: "Path to the docker file. Default is .docker/Dockerfile"
        default: .docker/Dockerfile
        type: string
      image-tags:
        description: "Image tags."
        required: true
        type: string
      image-labels:
        description: "Image labels."
        required: true
        type: string
      image-url:
        description: "Image url/name without registry."
        required: true
        type: string
      notify:
        description: "Enable mattermost notify. Default is true"
        default: "true"
        type: string
      artifact-name:
        description: "The artifact name to download."
        required: false
        type: string
      artifact-path:
        description: "The artifact path to extract the artifact into."
        required: false
        type: string
      vts:
        description: "Is this the vts image?"
        default: "false"
        type: string
      notification-channel:
        description: "The name of the channel where the notification happens."
        type: string
        default: "pdfeeddeploymentnotification"

    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      GREENBONE_REGISTRY:
        required: false
      GREENBONE_REGISTRY_USER:
        required: false
      GREENBONE_REGISTRY_TOKEN:
        required: false
      GREENBONE_REGISTRY_REPLICATION_USER:
        required: false
      GREENBONE_REGISTRY_REPLICATION_TOKEN:
        required: false
      MATTERMOST_WEBHOOK_URL:
        required: false

# INFO
# We cannot use a matrix here because job outputs from matrix jobs cannot be passed to other jobs.
# Due to cosign and the use of native runners, we cannot use the platform build mode from buildx anymore.
# This means we have to build our own multi-arch manifest.

jobs:
  build-amd64:
    runs-on: self-hosted-generic
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
      tags: ${{ steps.build-and-push.outputs.tags }}
      annotations: ${{ steps.build-and-push.outputs.annotations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref-name }}

      - name: Download Artifact ${{ inputs.artifact-name }} to ${{ inputs.artifact-path }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        if: inputs.artifact-name
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Print Tree of Build-Context
        run: tree ${{ inputs.build-context }}

      - name: Unpack vulnerability-tests feed content
        if: inputs.vts == 'true'
        run: |
          cd ${{ inputs.artifact-path }}
          tar -xJf vulnerability-tests.tar.xz && rm vulnerability-tests.tar.xz

      - name: Container build and push 2nd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-generic@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: raw,value=${{ inputs.ref-name || github.ref_name }}-amd64 # temporary tag that will be overwritten with the manifest upload
          image-platforms: linux/amd64
          image-flavor: latest=false
          registry: ${{ vars.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

  build-arm64:
    # At the moment we don't have enough arm runners to provide a run for every PR!
    if: github.event_name != 'pull_request'
    runs-on: self-hosted-generic-arm64
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
      tags: ${{ steps.build-and-push.outputs.tags }}
      annotations: ${{ steps.build-and-push.outputs.annotations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref-name }}

      - name: Download Artifact ${{ inputs.artifact-name }} to ${{ inputs.artifact-path }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        if: inputs.artifact-name
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Unpack vulnerability-tests feed content
        if: inputs.vts == 'true'
        run: |
          cd ${{ inputs.artifact-path }}
          tar -xJf vulnerability-tests.tar.xz

      - name: Container build and push 3rd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-generic@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: raw,value=${{ inputs.ref-name || github.ref_name }}-arm64 # temporary tag that will be overwritten with the manifest upload
          image-platforms: linux/arm64
          image-flavor: latest=false
          registry: ${{ vars.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

  create-multi-arch-manifest:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted-generic
    needs:
      - build-amd64
      - build-arm64
    steps:
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ vars.GREENBONE_REGISTRY }}/${{ inputs.image-url }}
          tags: ${{ inputs.image-tags }}

      - name: Create multi arch manifest
        uses: greenbone/actions/container-multi-arch-manifest@v3
        with:
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          cosign-tlog-upload: "false"
          annotations: |
            ${{ needs.build-amd64.outputs.annotations }}
            ${{ needs.build-arm64.outputs.annotations }}
          meta-tags: ${{ steps.meta.outputs.tags }}
          digests: |
            ${{ needs.build-amd64.outputs.digest }}
            ${{ needs.build-arm64.outputs.digest }}
          url: ${{ inputs.image-url }}
          registry: ${{ vars.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

  harbor-replication:
    if: github.event_name != 'pull_request'
    needs: create-multi-arch-manifest
    runs-on: self-hosted-generic
    steps:
      - name: Trigger harbor replication
        shell: bash
        run: |
          if ! [ '${{ secrets.GREENBONE_REGISTRY_REPLICATION_TOKEN }}' ]; then
            echo "Secret GREENBONE_REGISTRY_REPLICATION_TOKEN does not exist"
            exit 0
          fi
          curl -X POST \
            https://${{ vars.GREENBONE_REGISTRY }}/api/v2.0/replication/executions \
            -u '${{ secrets.GREENBONE_REGISTRY_REPLICATION_USER }}:${{ secrets.GREENBONE_REGISTRY_REPLICATION_TOKEN }}' \
            -H "Content-Type: application/json" \
            -d '{"policy_id": 1}'

  notify:
    needs:
      - build-amd64
      - build-arm64
      - create-multi-arch-manifest
    if: ${{ always() && startsWith(inputs.notify, 'true') }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-2nd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
      channel: ${{ inputs.notification-channel }}
    secrets: inherit
