name: Container build push 3rd gen

on:
  workflow_call:
    inputs:
      build-context:
        description: "Path to image build context. Default is ."
        default: .
        type: string
      build-docker-file:
        description: "Path to the docker file. Default is ./Dockerfile"
        default: ./Dockerfile
        type: string
      build-args:
        description: "Use these build-args for the docker build process. It is not possible to use github secrets in here! Use the action."
        default: ""
        type: string
      build-secrets:
        description: "Use these build-secrets for the docker build process. It is not possible to use github secrets in here! Use the action."
        default: ""
        type: string
      build-secret-greenbonebot:
        description: "Set the GREENBONE_BOT_PACKAGES_READ_TOKEN as image build secret. Default is false"
        default: "false"
        type: string
      service:
        description: "The name of the service to update. If not set, no service update will be done in the product compose files. Default is empty"
        default: ""
        type: string
      image-labels:
        description: "Image labels."
        required: true
        type: string
      image-url:
        description: "Image url/name without registry. Default is github.repository"
        default: "${{ github.repository }}"
        type: string
      notify:
        description: "Enable mattermost notify. Default is true"
        default: "true"
        type: string
      scout:
        description: "Enable docker scout sbom. Default is false"
        default: "false"
        type: string

    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      GREENBONE_BOT:
        required: false
      GREENBONE_BOT_PACKAGES_READ_TOKEN:
        required: false
      GREENBONE_BOT_PACKAGES_WRITE_TOKEN:
        required: false
      GREENBONE_BOT_TOKEN:
        required: false
      MATTERMOST_WEBHOOK_URL:
        required: false
      GREENBONE_REGISTRY:
        required: false
      GREENBONE_REGISTRY_USER:
        required: false
      GREENBONE_REGISTRY_TOKEN:
        required: false
      GREENBONE_REGISTRY_REPLICATION_USER:
        required: false
      GREENBONE_REGISTRY_REPLICATION_TOKEN:
        required: false

    outputs:
      digest:
        description: "The container digest"
        value: ${{ jobs.build.outputs.digest }}

jobs:
  meta:
    name: Meta Data
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.image-url.outputs.url }}
      name: ${{ steps.image-url.outputs.name }}
    steps:
      - name: Create image url
        id: image-url
        shell: bash
        run: |
          case "${{ inputs.image-url }}" in
            *"asset-management"*)
              url="opensight-asset-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"vulnerability-intelligence"*)
              url="opensight-lookout-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"scan-management"*)
              url="opensight-management-console-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"management-console"*)
              url="opensight-management-console-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"opensight-postgres"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"opensight-keycloak"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"opensight-keycloak-sidecar"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"opensight-ingress"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"opensight-opensearch"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"user-management"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *"opensight-notification-service"*)
              url="opensight-dev/$(basename ${{ inputs.image-url }})"
              ;;
            *)
              echo "No supported service in ${{ inputs.image-url }}"
              exit 1
              ;;
          esac
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "name=$(basename ${{ inputs.image-url }})" >> $GITHUB_OUTPUT

  build:
    name: Container build push 3rd gen
    needs: meta
    uses: greenbone/workflows/.github/workflows/container-push.yml@main
    with:
      build-context: ${{ inputs.build-context }}
      build-docker-file: ${{ inputs.build-docker-file }}
      build-args: ${{ inputs.build-args }}
      build-secrets: ${{ inputs.build-secrets }}
      build-secrets-name: ${{ contains(inputs.build-secret-greenbonebot, 'true') && 'GREENBONE_BOT_PACKAGES_READ_TOKEN' }}
      image-labels: ${{ inputs.image-labels }}
      image-urls: |
        ghcr.io/${{ inputs.image-url }}
        ${{ vars.GREENBONE_REGISTRY }}/${{ needs.meta.outputs.url }}
    secrets: inherit

  push-sbom:
    name: Scan image and push SBOM
    if: inputs.service && startsWith(github.ref, 'refs/tags/v')
    needs: build
    uses: greenbone/workflows/.github/workflows/generate-and-push-sbom-with-trivy-3rd-gen.yml@main
    with:
      image-url: "${{ vars.GREENBONE_REGISTRY }}/${{ needs.meta.outputs.url }}:${{ github.ref_name }}"
      image-registry-username-secret-name: "GREENBONE_REGISTRY_USER"
      image-registry-password-secret-name: "GREENBONE_REGISTRY_TOKEN"
      output-file-name: "${{ needs.meta.outputs.name }}.${{ github.ref_name }}.sbom.json"
      artifact-url: "${{ vars.GREENBONE_REGISTRY }}/${{ needs.meta.outputs.url }}-sbom:${{ github.ref_name }}"
    secrets: inherit

  automatix:
    if: inputs.service && startsWith(github.ref, 'refs/tags/v')
    needs:
      - meta
      - build
      - harbor-replication
    runs-on: ubuntu-latest
    steps:
      - name: Trigger product compose upgrade
        uses: greenbone/actions/trigger-workflow@v3
        with:
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          repository: greenbone/automatix
          workflow: push.yml
          inputs: '{"service": "${{ inputs.service }}", "image-url": "${{ needs.meta.outputs.url }}", "digest": "${{ needs.build.outputs.digest }}", "version": "${{ github.ref_name }}"}'

  notify:
    needs:
      - meta
      - build
      - push-sbom
      - harbor-replication
      - automatix
    if: ${{ !cancelled() && inputs.service && startsWith(github.ref, 'refs/tags/v') && startsWith(inputs.notify, 'true') }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-3rd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    secrets: inherit
