name: Sensor Build and Push

on:
  workflow_call:
    inputs:
      ref-name:
        description: "The ref to build a container image from. For example a tag v23.0.0."
        default: ${{ github.ref }}
        type: string
      build-context:
        description: "Path to image build context. Default is ."
        default: .
        type: string
      build-docker-file:
        description: "Path to the docker file. Default is .docker/Dockerfile"
        default: .docker/Dockerfile
        type: string
      image-tags:
        description: "Image tags."
        required: true
        type: string
      image-labels:
        description: "Image labels."
        required: true
        type: string
      image-url:
        description: "Image url/name without registry."
        required: true
        type: string
      notify:
        description: "Enable mattermost notify. Default is true"
        default: "true"
        type: string
      artifact-name:
        description: "The artifact name to download."
        required: false
        type: string
      artifact-path:
        description: "The artifact path to extract the artifact into."
        required: false
        type: string

    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      GREENBONE_REGISTRY:
        required: false
      GREENBONE_REGISTRY_USER:
        required: false
      GREENBONE_REGISTRY_TOKEN:
        required: false
      MATTERMOST_WEBHOOK_URL:
        required: false

# INFO
# We cannot use a matrix here because job outputs from matrix jobs cannot be passed to other jobs.
# Due to cosign and the use of native runners, we cannot use the platform build mode from buildx anymore.
# This means we have to build our own multi-arch manifest.

jobs:
  build-amd64:
    runs-on: self-hosted-generic
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
      tags: ${{ steps.build-and-push.outputs.tags }}
      annotations: ${{ steps.build-and-push.outputs.annotations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ inputs.ref-name }}

      - uses: actions/download-artifact@v4
        if: inputs.artifact-name
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}        

      - name: Container build and push 2nd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-generic@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: ${{ inputs.image-tags }}
          image-platforms: linux/amd64
          registry: ${{ secrets.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

  build-arm64:
    # At the moment we don't have enough arm runners to provide a run for every PR!
    if: github.event_name != 'pull_request'
    runs-on: self-hosted-generic-arm64
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
      tags: ${{ steps.build-and-push.outputs.tags }}
      annotations: ${{ steps.build-and-push.outputs.annotations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ inputs.ref-name }}

      - uses: actions/download-artifact@v4
        if: inputs.artifact-name
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Container build and push 3rd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-generic@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: ${{ inputs.image-tags }}
          image-platforms: linux/arm64
          registry: ${{ secrets.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

  create-multi-arch-manifest:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted-generic
    needs:
      - build-amd64
      - build-arm64
    steps:
      - name: Create multi arch manifest
        uses: greenbone/actions/container-multi-arch-manifest@v3
        with:
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          cosign-tlog-upload: "false"
          annotations: |
            ${{ needs.build-amd64.outputs.annotations }}
            ${{ needs.build-arm64.outputs.annotations }}
          tags: |
            ${{ needs.build-amd64.outputs.tags }}
            ${{ needs.build-arm64.outputs.tags }}
          digests: |
            ${{ needs.build-amd64.outputs.digest }}
            ${{ needs.build-arm64.outputs.digest }}
          url: ${{ inputs.image-url }}
          registry: ${{ secrets.GREENBONE_REGISTRY }}
          registry-username: ${{ secrets.GREENBONE_REGISTRY_USER }}
          registry-password: ${{ secrets.GREENBONE_REGISTRY_TOKEN }}

  notify:
    needs:
      - build-amd64
      - build-arm64
      - create-multi-arch-manifest
    if: ${{ !cancelled() && startsWith(github.ref, 'refs/tags/v')  && startsWith(inputs.notify, 'true') }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-3rd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    secrets: inherit
