name: Container build and push 3rd gen

on:
  workflow_call:
    inputs:
      build-context:
        description: "Path to image build context."
        type: string
        default: .
      build-docker-file:
        description: "Path to the docker file."
        type: string
        default: ./Dockerfile
      build-args:
        description: "Use these build-args for the docker build process. It is not possible to use secrets in here! Use the action."
        type: string
        default: ''
      image-labels:
        description: "Image labels."
        type: string
        required: true
      image-url:
        description: "Image url/name without registry."
        type: string
        required: true
      image-platforms: 
        description: "Image platforms to build for."
        type: string
        default: linux/amd64
    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: true
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: true
jobs:
  building:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Container build and push 3rd gen
        uses: greenbone/actions/container-build-push-3rd-gen@v2
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          build-args: ${{ inputs.build-args }}
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-platforms: ${{ inputs.image-platforms }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
