name: Container build and push ghcr.io

on:
  workflow_call:
    inputs:
      build-context: 
        description: "Path to image build context. Default: ."
        type: string
        default: .
      build-docker-file:
        description: "Path to the docker file. Default: ./Dockerfile"
        type: string
        default: ./Dockerfile
      build-args:
        description: "Use these build-args for the docker build process. It is not possible to use secrets in here! Use the action."
        type: string
        default: ''
      image-labels:
        description: "Image labels."
        type: string
        required: true
      image-url:
        description: "Image url/name without registry."
        type: string
        required: true
      image-tags:
        description: "Image tags."
        type: string
        required: true
      image-platforms: 
        description: "Image platforms to build for. Default: linux/amd64"
        type: string
        default: linux/amd64

jobs:
  building:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Container build and push ghcr.io
        uses: greenbone/actions/container-build-push-ghcr@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          build-args: ${{ inputs.build-args }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: ${{ inputs.image-tags }}
          image-platforms: ${{ inputs.image-platforms }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
