name: Deploy on PyPI

on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
    inputs:
      pypi-url:
        description: 'URL to the project on PyPI.org'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: ${{ inputs.pypi-url }}
    steps:
      - name: Build and publish to PyPI
        uses: greenbone/actions/pypi-upload@a1883bd24d2d921426b3f06413e84606ecd43bdd # v3.27.11
        with:
          pypi-token: ${{ secrets.PYPI_TOKEN }}
