name: Deploy docs to GitHub Pages

on:
  workflow_call:
    inputs:
      artifact-name:
        description: " artifact names to download"
        required: true
        type: string
      # path:
      #   description: " artifact paths"
      #   required: true
      #   type: string
      # retention-day:
      #     required: false
      #     type: number
      #     default: 2

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name}}
        path: artifact-dir
    - name: verify artifacts
      run: |
        pwd
        ls -R artifact-dir
    - name: Extract artifact
      run: |
        echo "${{ inputs.artifact-name }}.tar.xz"
        tar --xz -xvf artifact-dir/${{ inputs.artifact-name }}.tar.xz -C artifact-dir/
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: artifact-dir
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      # with:
      #   name: ${{ inputs.artifact-name  }}-pages
