name: Deploy docs to GitHub Pages

on:
  workflow_call:
    inputs:
      artifact-name:
        description: " artifact names "
        required: true
        type: string
      artifact-path:
        description: " artifact paths"
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: print artifacts
      run: |
        echo "artifact-name: ${{ inputs.artifact-name }}"
        echo "artifact-path: ${{ github.workspace }}/${{ inputs.artifact-name }}"
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        artifact-name: ${{ inputs.artifact-name  }}
        artifact-path: ${{ inputs.artifact-path  }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
