name: Container build and push 3rd gen

on:
  workflow_call:
    inputs:
      build-context:
        description: "Path to image build context. Default is ."
        default: .
        type: string
      build-docker-file:
        description: "Path to the docker file. Default is ./Dockerfile"
        default: ./Dockerfile
        type: string
      build-args:
        description: "Use these build-args for the docker build process. It is not possible to use github secrets in here! Use the action."
        default: ""
        type: string
      build-secrets:
        description: "Use these build-secrets for the docker build process. It is not possible to use github secrets in here! Use the action."
        default: ""
        type: string
      build-secret-greenbonebot:
        description: "Set the GREENBONE_BOT_PACKAGES_READ_TOKEN as image build secret. Default is false"
        default: "false"
        type: string
      helm-chart:
        description: "The name of the helm chart to update. If not set, no chart update will be done. Default is empty"
        default: ""
        type: string
      init-container:
        description: "Update the tag from an init container. Set the parent key from the values.yaml. Default is empty"
        type: string
        required: false
      init-container-digest:
        description: "The init container digest for the helm chart tag."
        type: string
        required: false
      image-labels:
        description: "Image labels."
        required: true
        type: string
      image-url:
        description: "Image url/name without registry."
        required: true
        type: string
      image-platforms:
        description: "Image platforms to build for. Default is linux/amd64"
        default: linux/amd64
        type: string
      use-greenbonebot:
        description: "Use the greenbonebot token as registry login. Default is false"
        default: "false"
        type: string
      notify:
        description: "Enable mattermost notify. Default is true"
        default: "true"
        type: string
        
    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      GREENBONE_BOT:
        required: false
      GREENBONE_BOT_PACKAGES_READ_TOKEN:
        required: false
      GREENBONE_BOT_PACKAGES_WRITE_TOKEN:
        required: false
      GREENBONE_BOT_TOKEN:
        required: false
      MATTERMOST_WEBHOOK_URL:
        required: false

    outputs:
      digest:
        description: "The container digest"
        value: ${{ jobs.building-container.outputs.digest }}

jobs:
  building-container:
    runs-on: "ubuntu-latest"
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Container build and push 3rd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-3rd-gen@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          build-args: ${{ inputs.build-args }}
          build-secrets: ${{ contains(inputs.build-secret-greenbonebot, 'true') && format('GREENBONE_BOT_PACKAGES_READ_TOKEN={0}', secrets.GREENBONE_BOT_PACKAGES_READ_TOKEN) || inputs.build-secrets }}
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-platforms: ${{ inputs.image-platforms }}
          registry-password: ${{ contains(inputs.use-greenbonebot, 'true') && secrets.GREENBONE_BOT_TOKEN || secrets.GITHUB_TOKEN }}

  building-helm-chart:
    if: (inputs.helm-chart) && (startsWith(github.ref, 'refs/tags/v'))
    needs:
      - building-container
    uses: greenbone/workflows/.github/workflows/helm-build-push-3rd-gen.yml@main
    with:
      chart: ${{ inputs.helm-chart }}
      container-digest: ${{ needs.building-container.outputs.digest }}
      init-container: ${{ inputs.init-container }}
      init-container-digest: ${{ inputs.init-container-digest }}
    secrets: inherit

  notify:
    needs:
      - building-container
      - building-helm-chart
    if: ${{ !cancelled() && startsWith(github.ref, 'refs/tags/v')  && startsWith(inputs.notify, 'true') }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-3rd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    secrets: inherit
