name: Helm chart release on tag

on:
  workflow_call:
    charts:
      type: str
      description: "What Charts should be updated? Can be comma separated list."
    secrets: inherit

jobs:
  release-helm-chart:
    name: Release helm chart
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart:
          [ split(${{ github.event.inputs.charts }}, ',') ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from tag
        run: |
          vtag='${{github.ref_name}}'
          echo "tag=${vtag:1}" >> $GITHUB_OUTPUT

      - name: Run helm version upgrade
        uses: greenbone/actions/helm-version-upgrade@v2
        with:
          chart-path: ${{ github.workspace }}/charts/${{ matrix.chart }}
          chart-version: ${{ steps.version.outputs.tag }}

      - name: Print Chart.yaml
        run: |
          cat '${{ github.workspace }}/charts/${{ matrix.chart }}/Chart.yaml'

      - name: Upload to github registry
        uses: greenbone/actions/helm-build-push@v2
        with:
          chart-name: ${{ matrix.chart }}
          registry: ${{ vars.IMAGE_REGISTRY }}
          registry-subpath: helm-charts/
          registry-user: ${{ secrets.GREENBONE_BOT }}
          registry-token: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}

      - name: Trigger product helm chart upgrade
        uses: greenbone/actions/trigger-workflow@v2
        with:
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          repository: "greenbone/product-helm-chart"
          workflow: product-chart-upgrade.yml
          inputs: '{"chart": "${{ matrix.chart }}", "tag": "${{ github.ref_name }}"}'
