name: Helm chart release on tag 3rd gen

on:
  workflow_call:
    inputs:
      chart:
        description: "The name of the helm chart to update."
        type: string
        required: true
      chart-version:
        description: "The service chart version to set."
        type: string
        required: false
      container-digest:
        description: "The container digest for the helm chart tag."
        type: string
        required: true
      init-container:
        description: "Update the tag from an init container. Set the parent key from the values.yaml. Default: empty"
        type: string
        required: false
      init-container-digest:
        description: "The init container digest for the helm chart tag."
        type: string
        required: false
    # Dependabot don't have this secrets and on PR's this secrets are not needed.
    secrets:
      GREENBONE_BOT:
        required: false
      GREENBONE_BOT_PACKAGES_WRITE_TOKEN:
        required: false
      GREENBONE_BOT_TOKEN:
        required: false

jobs:
  release-helm-chart:
    name: Release helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version from tag
        id: version
        run: |
          vtag='${{ inputs.chart-version }}'
          echo "tag=${vtag:1}" >> $GITHUB_OUTPUT
      - name: Run helm version upgrade
        uses: greenbone/actions/helm-version-upgrade@v3
        with:
          chart-path: ${{ github.workspace }}/charts/${{ inputs.chart }}
          chart-version: ${{ steps.version.outputs.tag }}
          image-tag: "${{ steps.version.outputs.tag }}@${{ inputs.container-digest }}"
      - name: Upgrade init container tag
        if: inputs.init-container && inputs.init-container-digest
        uses: greenbone/actions/helm-version-upgrade@v3
        with:
          chart-path: ${{ github.workspace }}/charts/${{ inputs.chart }}
          chart-version: ${{ steps.version.outputs.tag }}
          image-tag: "${{ steps.version.outputs.tag }}@${{ inputs.init-container-digest }}"
          overwrite-parent-key-image-tag: "${{ inputs.init-container }}"
      - name: Print Chart.yaml
        run: |
          cat '${{ github.workspace }}/charts/${{ inputs.chart }}/Chart.yaml'
      - name: Print values.yaml
        run: |
          cat '${{ github.workspace }}/charts/${{ inputs.chart }}/values.yaml'
      - name: Upload to github registry
        uses: greenbone/actions/helm-build-push@v3
        with:
          chart-name: ${{ inputs.chart }}
          registry: ${{ vars.IMAGE_REGISTRY }}
          registry-subpath: helm-charts/
          registry-user: ${{ secrets.GREENBONE_BOT }}
          registry-token: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}
