name: Container build and push 3rd gen

on:
  workflow_call:
    inputs:
      build-context:
        description: "Path to image build context. Default is ."
        default: .
        type: string
      build-docker-file:
        description: "Path to the docker file. Default is ./Dockerfile"
        default: ./Dockerfile
        type: string
      build-args:
        description: "Use these build-args for the docker build process. It is not possible to use github secrets in here! Use the action."
        default: ""
        type: string
      build-secrets:
        description: "Use these build-secrets for the docker build process. It is not possible to use github secrets in here! Use the action."
        default: ""
        type: string
      build-secret-greenbonebot:
        description: "Set the GREENBONE_BOT_PACKAGES_READ_TOKEN as image build secret. Default is false"
        default: "false"
        type: string
      helm-chart:
        description: "The name of the helm chart to update. If not set, no chart update will be done. Default is empty"
        default: ""
        type: string
      init-container:
        description: "Update the tag from an init container. Set the parent key from the values.yaml. Default is empty"
        type: string
        required: false
      init-container-digest:
        description: "The init container digest for the helm chart tag."
        type: string
        required: false
      image-labels:
        description: "Image labels."
        required: true
        type: string
      image-url:
        description: "Image url/name without registry."
        required: true
        type: string
      image-platforms:
        description: "Image platforms to build for. Default is linux/amd64"
        default: linux/amd64
        type: string
      use-greenbonebot:
        description: "Use the greenbonebot token as registry login. Default is false"
        default: "false"
        type: string
      notify:
        description: "Enable mattermost notify. Default is true"
        default: "true"
        type: string
      scout:
        description: "Enable docker scout sbom. Default is false"
        default: "false"
        type: string

    secrets:
      COSIGN_KEY_OPENSIGHT:
        required: false
      COSIGN_KEY_PASSWORD_OPENSIGHT:
        required: false
      GREENBONE_BOT:
        required: false
      GREENBONE_BOT_PACKAGES_READ_TOKEN:
        required: false
      GREENBONE_BOT_PACKAGES_WRITE_TOKEN:
        required: false
      GREENBONE_BOT_TOKEN:
        required: false
      MATTERMOST_WEBHOOK_URL:
        required: false
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

    outputs:
      digest:
        description: "The container digest"
        value: ${{ jobs.building-container.outputs.digest }}

jobs:
  building-container:
    runs-on: "ubuntu-latest"
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Container build and push 3rd gen
        id: build-and-push
        uses: greenbone/actions/container-build-push-3rd-gen@v3
        with:
          build-context: ${{ inputs.build-context }}
          build-docker-file: ${{ inputs.build-docker-file }}
          build-args: ${{ inputs.build-args }}
          build-secrets: ${{ contains(inputs.build-secret-greenbonebot, 'true') && format('GREENBONE_BOT_PACKAGES_READ_TOKEN={0}', secrets.GREENBONE_BOT_PACKAGES_READ_TOKEN) || inputs.build-secrets }}
          cosign-key: ${{ secrets.COSIGN_KEY_OPENSIGHT }}
          cosign-key-password: ${{ secrets.COSIGN_KEY_PASSWORD_OPENSIGHT }}
          # The tlog function does not currently support an ed25519 key.
          cosign-tlog-upload: "false"
          image-url: ${{ inputs.image-url }}
          image-labels: ${{ inputs.image-labels }}
          image-tags: |
            # create container tag for git tags
            type=ref,event=tag,value=latest
            type=match,pattern=v(.*),group=1
            type=ref,event=pr
            # use unstable for main branch
            type=raw,value=unstable,enable={{is_default_branch}}
          image-platforms: ${{ inputs.image-platforms }}
          registry: "ghcr.io"
          registry-username: ${{ github.actor }}
          registry-password: ${{ contains(inputs.use-greenbonebot, 'true') && secrets.GREENBONE_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          scout-user: ${{ contains(inputs.scout, 'true') && secrets.DOCKERHUB_USERNAME || '' }}
          scout-password: ${{ contains(inputs.scout, 'true') && secrets.DOCKERHUB_TOKEN || '' }}

  building-service-chart:
    if: (inputs.helm-chart) && (startsWith(github.ref, 'refs/tags/v'))
    needs:
      - building-container
    runs-on: "ubuntu-latest"
    steps:
      - name: Trigger service helm chart upgrade
        uses: greenbone/actions/trigger-workflow@v3
        with:
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          repository: "greenbone/product-helm-chart"
          workflow: "service-chart-upgrade.yml"
          inputs: '{"chart": "${{ inputs.helm-chart }}", "chart-version": "${{ github.ref_name }}", "container-digest": "${{ needs.building-container.outputs.digest }}", "init-container": "${{ inputs.init-container }}", "init-container-digest": "${{ inputs.init-container-digest }}"}'

  building-product-chart:
    if: (inputs.helm-chart) && (startsWith(github.ref, 'refs/tags/v'))
    needs:
      - building-container
      - building-service-chart
    runs-on: "ubuntu-latest"
    steps:
      - name: Trigger product helm chart upgrade
        uses: greenbone/actions/trigger-workflow@v3
        with:
          token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          repository: "greenbone/product-helm-chart"
          workflow: "product-chart-upgrade.yml"
          inputs: '{"chart": "${{ inputs.helm-chart }}", "tag": "${{ github.ref_name }}"}'

  notify:
    needs:
      - building-container
      - building-service-chart
      - building-product-chart
    if: ${{ !cancelled() && startsWith(github.ref, 'refs/tags/v')  && startsWith(inputs.notify, 'true') }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-3rd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    secrets: inherit
