name: Notify Mattermost Feed Deployment

on:
  workflow_call:
    inputs:
      commit:
        description: "The commit used by the github checkout action. Default: github.sha"
        type: string
        default: ${{ github.sha }}
      exit-with-status:
        description: "Exit this job/workflow with the monitored job status. Options: true or false. Default: true"
        type: string
        default: "true"
      highlight:
        description: "Mattermost highlight. Default: devops"
        type: string
        default: "devops"
      status:
        description: "The monitored job, job status."
        type: string
        required: true
      shortline:
        description: "Mattermost use shortline mode. Default: true"
        type: string
        default: "true"
    secrets:
      MATTERMOST_WEBHOOK_URL:
        required: true
      MATTERMOST_FEED_CHANNEL:
        required: true

jobs:
  notify-mattermost:
    runs-on:
      - self-hosted
      - self-hosted-generic
    if: ${{ !cancelled() }}
    steps:
      - name: Notify Mattermost Feed Deployment
        uses: greenbone/actions/mattermost-notify@45b6e84c655954002872d0ac6c8d31b2f213c9a0 # v3.27.17
        with:
          url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: ${{ secrets.MATTERMOST_FEED_CHANNEL }}
          highlight: ${{ inputs.highlight }}
          branch: ${{ github.ref_name }}
          commit: ${{ inputs.commit }}
          workflow: ${{ github.run_id }}
          workflow-name: ${{ github.workflow }}
          status: ${{ inputs.status }}
          shortline: ${{ inputs.shortline }}

      - name: Exit with monitored job status
        if: inputs.exit-with-status == 'true' && inputs.status != 'success'
        run: |
          echo "Monitored job failed. Exit job/workflow with failure"
          exit 1
